"""Add is_active column to algorithms table

Revision ID: 1748660eab65
Revises: initial
Create Date: 2025-04-15 18:29:38.970492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1748660eab65'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithms', 'is_active')
    # ### end Alembic commands ### 